# Generated by Django 4.2.7 on 2023-11-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_quest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Details',
        ),
    ]
