# Generated by Django 4.2.7 on 2023-12-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('traffic_goal', models.IntegerField()),
                ('prizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_quest', to='prize.prize')),
            ],
        ),
    ]
