# Generated by Django 4.2.7 on 2023-12-17 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_quest', '0004_remove_trafficquest_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficquest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
