# Generated by Django 4.2.7 on 2023-12-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_quest', '0006_remove_trafficquest_id_alter_trafficquest_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficquest',
            old_name='uuid',
            new_name='id',
        ),
    ]
