# Generated by Django 4.2.7 on 2023-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('redemption_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
