# Generated by Django 4.2.7 on 2023-12-12 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_quest', '0004_remove_trafficquest_prizes'),
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='traffic_quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='traffic_quest.trafficquest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2010, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='prize',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
