# Generated by Django 4.2.7 on 2023-12-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0003_prize_traffic_quest_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='traffic_quest_old',
        ),
    ]
