# Generated by Django 4.2.7 on 2023-12-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize_award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizeentree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prizeentree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
